spring:
  application:
    name: spring-ai
  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
    openai:
      api-key: ${OPEN_API_KEY}

#  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        model: llama3.2:1b

server:
  port: 9292


